PREFIX clonto: <http://myCLOnto.de/> 
SELECT ?categoryname
(COUNT(?mcategory) as ?mediatorDepth)
?depth
WHERE {
	?scategory clonto:name "Computer languages" .
	?scategory clonto:hasSubCategory* ?mcategory .
	?mcategory clonto:hasSubCategory+ ?category .
	?category clonto:depth ?depth .
	?category clonto:name ?categoryname .
}
GROUP BY ?categoryname ?depth
ORDER BY ?howManym