PREFIX clonto: <http://myCLOnto.de/>
SELECT 
?categoryname 
?subcategoryname
?categorytentitycount
?subcategorytentitycount
(?categorytentitycount-?subcategorytentitycount as ?entitydifference)
WHERE {
	?category clonto:depth ?depth .
	?category clonto:hasSubCategory ?subcategory .
	?category clonto:name ?categoryname .
	?subcategory clonto:name ?subcategoryname .
	
	{SELECT ?category (COUNT(?tentity) as ?categorytentitycount)
	WHERE{
	{SELECT DISTINCT ?category ?tentity
     WHERE  {  
		?category (clonto:hasSubCategory*/clonto:hasEntity) ?tentity . 
	}
    }
	}
	group by ?category
	}
	
	{SELECT ?subcategory (COUNT(?tsentity) as ?subcategorytentitycount)
	WHERE{
	{SELECT DISTINCT ?subcategory ?tsentity
     WHERE  {  
		?subcategory (clonto:hasSubCategory*/clonto:hasEntity) ?tsentity . 
	}
    }
	}
	group by ?subcategory
	}
}
GROUP BY ?categoryname ?subcategoryname ?categorytentitycount ?subcategorytentitycount
ORDER BY ?entitydifference