PREFIX clonto: <http://myCLOnto.de/> 
SELECT ?categoryname ?howMany 
WHERE {
	FILTER EXISTS{ ?cat clonto:hasSubCategory ?category . }
	?category clonto:name ?categoryname .
    {SELECT ?category (COUNT(?entity) AS ?howMany)  
     WHERE  {  
		?category clonto:hasEntity ?entity . 
	}
    group by ?category}
    FILTER(?howMany > 30)
}
ORDER BY ?howMany