PREFIX : <http://myCLOnto.de/> 
SELECT 
?typename 
(COUNT(?entity) as ?NumberOfEntities)
(COUNT(?subtype) as ?NumberOfSubtypes)
(?NumberOfEntities + ?NumberOfSubtypes as ?howmany)
WHERE {
	?type :depth ?depth .
	?type :name ?typename .
	
	{SELECT ?type ?entity
	WHERE{
		?type :hasInstance ?entity .
	}
	}
	
	UNION
	
	{SELECT ?type ?subtype
	WHERE{
		?type :hasSubtype ?subtype .
	}
	}
}
GROUP BY ?typename
HAVING (?howmany < 5)
ORDER BY ?howmany