PREFIX clonto: <http://myCLOnto.de/> 
SELECT DISTINCT ?cname ?ename  
WHERE {  
	?category clonto:depth ?depth .
    ?category clonto:name ?cname . 
	FILTER(regex(STR(?category),"Category"))
	FILTER(regex(STR(?entity),"Entity"))
    ?entity clonto:name ?ename .
    FILTER contains(?ename, ?cname)
    FILTER NOT EXISTS{ 
		?category clonto:hasSubCategory*/clonto:hasEntity ?entity
	}
}
ORDER BY ?category