PREFIX : <http://myCLOnto.de/> 
SELECT ?entityname (COUNT(?information) as ?howMany)
WHERE {  
	?entity :hasInformation ?information .
	?entity :name ?entityname .
}
GROUP BY ?entityname
HAVING (?howMany > 1)
ORDER BY ?howMany