PREFIX : <http://myCLOnto.de/> 
SELECT ("https://en.wikipedia.org/wiki/" + replace(?entityname," ","_")+" " as ?fname) (COUNT(?information) as ?howMany)
WHERE {  
	?entity :hasInformation ?information .
	?entity :name ?entityname .
}
GROUP BY ?entityname
HAVING (?howMany > 1)
ORDER BY ?howMany