PREFIX : <http://myCLOnto.de/> 
SELECT ?entityname ?subtypename ?typename 
WHERE {  
    ?type :hasSubtype+ ?subtype .
    ?type :hasInstance ?entity .
    ?subtype :hasInstance ?entity . 
	?entity :name ?entityname .
	?type :name ?typename .
	?subtype :name ?subtypename .
}
ORDER BY ?typename