PREFIX : <http://myCLOnto.de/> 
SELECT ?entityname ?topic
WHERE {
	?entity :name ?entityname .
    ?entity :hasInformation ?information .
    ?information :topic ?topic . 
    FILTER NOT EXISTS{ 
        ?entity :hasInformation ?information2 .
        ?information2 :topic ?topic2 .
        FILTER (contains(?topic2,"program") 
                || contains(?topic2, "standard")
                || contains(?topic2, "file format"))
    }
    FILTER NOT EXISTS{
        ?entity :hasInformation ?information2 .
        ?information2 :hasProperty ?at .
        ?at :name ?atname .
        FILTER (contains(?atname, "programming")) 
    }
}
ORDER BY ?topic