PREFIX : <http://myCLOnto.de/> 
SELECT ?entityname  (COUNT(?dtype) as ?howManyDistantTypes) (COUNT(?rtype) as ?howManyReachableTypes) ((?howManyDistantTypes-?howManyReachableTypes) as ?difference)
WHERE {
    {SELECT DISTINCT ?entity ?dtype
    WHERE {
        ?entity ^:hasInstance ?dtype . 
        FILTER NOT EXISTS{ 
			?dtype :depth ?depth .
		}
    }
    }
	UNION
	{SELECT DISTINCT ?entity ?rtype
    WHERE {
        ?entity ^:hasInstance ?rtype . 
        ?rtype :depth ?depth .
    }
    }
	?entity :name ?entityname .
}
GROUP BY ?entityname
HAVING(?diff>0)
ORDER BY ?diff