PREFIX clonto: <http://myCLOnto.de/>
SELECT DISTINCT ?categoryname ?howmanySub
WHERE {
	?categoryS clonto:hasSubCategory ?category .
	FILTER NOT EXISTS{?category clonto:hasEntity ?entity}
	{SELECT ?category (COUNT(?subcat) as ?howmanySub)
	WHERE {
		?category clonto:hasSubCategory ?subcat .
	}
	GROUP BY ?category
	HAVING (?howmanySub < 8)
	}
	?category clonto:name ?categoryname .
}
ORDER BY ?howmanySub