PREFIX : <http://myCLOnto.de/> 
DELETE {
  ?t ?r ?n .
}
WHERE{ 
  FILTER(regex(STR(?t), "Type"))
  FILTER NOT EXISTS { ?t ^:hasSubtype ?supert }
  FILTER NOT EXISTS { ?t :name "Computer languages" }
  ?t ?r ?n .
}