PREFIX : <http://myCLOnto.de/> 
INSERT { 
		<http://myCLOnto.de/Entity#1387> :name "MetaPost" .
		?type1 :hasInstance <http://myCLOnto.de/Entity#1387> .
		?type2 :hasInstance <http://myCLOnto.de/Entity#1387> .
		?type3 :hasInstance <http://myCLOnto.de/Entity#1387> .
}
WHERE {  
    ?type1 :name "Declarative programming languages" .
	?type2 :name "Vector graphics markup languages" .
	?type3 :name "Domain-specific programming languages" .
}