PREFIX clonto: <http://myCLOnto.de/> 
DELETE { ?entity clonto:hasAttributeSet ?attributeset . }
WHERE { ?attributeset clonto:name ?attributesetname .
		?entity clonto:hasAttributeSet ?attributeset .
		?entity clonto:name ?entityname .
}