PREFIX clonto: <http://myCLOnto.de/> 
DELETE { ?atset clonto:hasAttribute ?property . }
WHERE{ 
	?atset clonto:name ?atsetname .
	?property clonto:name ?attributename .
	?atset clonto:hasAttribute ?property .
}