PREFIX : <http://myCLOnto.de/> 
INSERT {
  ?supertype :hasSubtype ?subtype .
}
WHERE{
  FILTER(regex(STR(?subtype),"Type") && regex(STR(?supertype),"Type"))
  ?subtype :name ?subtypename .
  ?supertype :name ?newsupertypename . }