PREFIX : <http://myCLOnto.de/> 
DELETE { ?sinfo :hasProperty ?property . }
INSERT { ?tinfo :hasProperty ?property . }
WHERE{ 
	?sinfo :name ?infoname .
	?property :name ?propertyname .
	?sinfo :hasProperty ?property .
    ?tinfo :name ?tinfoname .
}