PREFIX : <http://myCLOnto.de/> 
DELETE { ?supertype :hasSubtype ?subtype }
WHERE {
    ?supertype :hasSubtype ?subtype . 
    ?supertype :hasSubtype+ ?type .
    ?type :hasSubtype ?subtype .
	?subtype :name ?subtypename .
	?type :name ?typename .
	?supertype :name ?supertypename .
}