PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://myCLOnto.de/> 
SELECT ?ename ?t1name ?t2name
WHERE {
    ?cl :name "Computer languages" .
    ?cl :hasSubCategory ?topcategory1 .
    ?cl :hasSubCategory ?topcategory2 .
    
    FILTER EXISTS{
        ?topcategory1 :hasSubCategory*/:hasEntity ?entity .
        ?topcategory2 :hasSubCategory*/:hasEntity ?entity .
    }
    FILTER NOT EXISTS{
        ?topcategory1 :hasSubCategory* ?topcategory2 .
    }
    FILTER NOT EXISTS{
        ?topcategory2 :hasSubCategory* ?topcategory1 .
    }
    ?topcategory1 :name ?t1name .
    ?topcategory2 :name ?t2name .
    FILTER(?t1name < ?t2name)
    ?entity :name ?ename .
}
ORDER BY ?t2name