PREFIX : <http://myCLOnto.de/> 
SELECT DISTINCT ("https://en.wikipedia.org/wiki/" + 
  replace(?name," ","_","i") as ?fname)
WHERE {
    ?el :name "Programming languages created in 1978" .
	?t :hasSubtype ?el .
    ?t2 :hasSubtype ?t .
    ?t :name ?name .
}
ORDER BY ?name