PREFIX : <http://myCLOnto.de/> 
SELECT 
?howManyNodes
(COUNT(?UnreachableType) as ?howManyUT)  
(?howManyTypes-?howManyUT as ?howManyReachableTypes)
?howManyEntities
?howManyTypes 
(?howManySubtypes+?howManyInstances+?howManyInformation+?howManyProperties+?howManyHasMainEntity as ?howManyEdges) 
(?howManySubtypes+?howManyInstances+?howManyInformation+?howManyProperties+?howManyNodes+?howManyDepth+?howManyTopic+?howManyHasMainEntity as ?howManyEdgesTotal) 
(?howManyNodes/?howManyEdges as ?EdgeNodeRatio) 
(?howManyEdges-?howManyNodes+1 as ?Treeimpurity) 
?howManySubtypes 
?howManyInstances 
?howManyInformation
?howManyProperties
?howManyDepth
?howManyTopic
?howManyValue
?howManyHasMainEntity
WHERE {
	
	{SELECT (COUNT(?resource) AS ?howManyNodes)  
     WHERE  {
		?resource :name ?name .
	}
    }
	
	{SELECT (COUNT(?resource) AS ?howManyTypes)
	WHERE {
		?resource :name ?name .
		FILTER(regex(STR(?resource),"Type"))
	}
	}
	
	{SELECT (COUNT(?resource) AS ?howManyEntities)
	WHERE {
		?resource :name ?name .
		FILTER(regex(STR(?resource),"Entity"))
	}
	}
	
	{SELECT DISTINCT ?UnreachableType   
     WHERE  {
        ?UnreachableType :name ?name .
		FILTER(regex(STR(?UnreachableType),"Type"))
		FILTER NOT EXISTS{
            ?cl :name "Computer languages" .
            ?cl :hasSubtype* ?UnreachableType .
		}
	}
    }
	
	{SELECT (COUNT(?node2) as ?howManySubtypes)
	WHERE {
		?node1 :hasSubtype ?node2 .
	}
	}
	
	
	
	{SELECT (COUNT(?node2) as ?howManyInstances)
	WHERE {
		?node1 :hasEntity ?node2 .
	}
	}
	
	
	
	{SELECT (COUNT(?node2) as ?howManyInformation)
	WHERE {
		?node1 :hasInformation ?node2 .
	}
	}
	
	
	{SELECT (COUNT(?node2) as ?howManyProperties)
	WHERE {
		?node1 :hasAttribute ?node2 .
	}
	}
	
	{SELECT (COUNT(?node2) as ?howManyDepth)
	WHERE {
		?node1 :depth ?node2 .
	}
	}
	
	{SELECT (COUNT(?node2) as ?howManyTopic)
	WHERE {
		?node1 :topic ?node2 .
	}
	}
	
	{SELECT (COUNT(?node2) as ?howManyValue)
	WHERE {
		?node1 :topic ?node2 .
	}
	}
	
	{SELECT (COUNT(?node2) as ?howManyHasMainEntity)
	WHERE {
		?node1 :hasMainEntity ?node2 .
	}
	}
	
}
GROUP BY ?howManyNodes ?howManyTypes ?howManyEntities ?howManyUT ?howManyEdges ?howManySubtypes ?howManyInstances ?howManyInformation ?howManyProperties ?howManyDepth ?howManyTopic ?howManyValue ?howManyHasMainEntity
